apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: afn-app
  namespace: default
spec:
  dnsNames:
    - africannames.app
  secretName: afn-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer