apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
  namespace: afn_cluster
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: africannamesfront
                port:
                  number: 80
            path: /
            pathType: Prefix