image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

build:
  image: gradle:6.0-jdk11-alpine
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

package:
  stage: package
  script:
    - docker build -t registry.gitlab.com/african-names/back/african-names .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/african-names/back/african-names

deploy_staging:
  tags:
    - dev
  stage: deploy
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no 78.192.91.3 docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com 
    - ssh -o StrictHostKeyChecking=no 78.192.91.3 docker pull registry.gitlab.com/mathflake/api
    - ssh -o StrictHostKeyChecking=no 78.192.91.3 "docker container stop mathflake_api && docker container rm mathflake_api || true"
    - ssh -o StrictHostKeyChecking=no 78.192.91.3 docker run --name mathflake_api -p 80:80 -d registry.gitlab.com/mathflake/api

  environment: dev
  only:
    - develop
