image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

build:
  image: gradle:6.8.3-jdk11-openj9
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

package:
  stage: package
  script:
    - ./gradlew bootBuildImage --imageName="$CI_REGISTRY_IMAGE"
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push $CI_REGISTRY_IMAGE

deploy_staging:
  tags:
    - dev
  stage: deploy
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no 78.192.91.3 docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com 
    - ssh -o StrictHostKeyChecking=no 78.192.91.3 docker pull $CI_REGISTRY_IMAGE
    - ssh -o StrictHostKeyChecking=no 78.192.91.3 "docker container stop african_name_api && docker container rm african_name_api || true"
    - ssh -o StrictHostKeyChecking=no 78.192.91.3 docker run --name african_name_api -p 80:80 -d $CI_REGISTRY_IMAGE
  environment: dev
  only:
    - develop
