image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  tags:
    - dev
  image: gradle:6.8.3-jdk11-openj9
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar

package:
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    REPOSITORY: $CI_REGISTRY/african-names/back/african-names
  stage: package
  image: azul/zulu-openjdk:11.0.10
  services:
    - docker:dind
  script:
    - apt-get update
    - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt-get update -y
    - apt-get install -y docker-ce
    - service docker start
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build --pull -t $REPOSITORY:latest .
    - docker push $REPOSITORY:latest
    - docker push $REPOSITORY

deploy_staging:
  tags:
    - dev
  stage: deploy
  variables:
    DOCKER_HOST: ssh://tooflex@$DEV_HOST:8082
  before_script:
    # Configure SSH
    - export ENV=dev
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "${SSH_DEV_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #- ssh-keyscan -t rsa $DEV_HOST >> ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY


  script:
    - echo setting up env $ENV
    - docker compose pull
    - docker compose --env-file $env_dev up -d --force-recreate
  after_script:
    - docker logout registry.gitlab.com
  environment: dev
  only:
    - dev
