#cloudbuild.yaml
steps:
  - name: 'docker/compose:1.19.0'
    args: ['up', '-d']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'africannameswebapp', '--image', 'gcr.io/$GCP_PROJECT_ID/africannameswebapp', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated', '--member', 'allUsers', '--role', 'roles/run.invoker']

images: ['gcr.io/$PROJECT_ID/$REPO_NAME:latest']
