#cloudbuild.yaml
steps:
  - name: 'docker/compose:1.19.0'
    args: ['up', '-d']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']
    env:
      - 'AFN_POSTGRES_USER=${AFN_POSTGRES_USER}'
      - 'AFN_POSTGRES_PASSWORD=${AFN_POSTGRES_PASSWORD}'
      - 'AFN_POSTGRES_DB=${AFN_POSTGRES_DB}'
      - 'AFN_POSTGRES_HOST=${AFN_POSTGRES_HOST}'
      - 'AFN_POSTGRES_PORT=${AFN_POSTGRES_PORT}'
      - 'AFN_APP_USER=${AFN_APP_USER}'
      - 'AFN_APP_PASSWORD=${AFN_APP_PASSWORD}'
      - 'AFN_ENV=${AFN_ENV}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', $SERVICE_NAME, '--image', 'gcr.io/$GCP_PROJECT_ID/$SERVICE_NAME', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated', '--member', 'allUsers', '--role', 'roles/run.invoker']

images: ['gcr.io/$PROJECT_ID/$REPO_NAME:latest']
