#cloudbuild.yaml
steps:
  - name: 'docker/compose:1.19.0'
    args: ['-f', 'docker-compose.yml', 'up', '-d']
    env:
      - 'AFN_POSTGRES_USER=${_AFN_POSTGRES_USER}'
      - 'AFN_POSTGRES_PASSWORD=${_AFN_POSTGRES_PASSWORD}'
      - 'AFN_POSTGRES_DB=${_AFN_POSTGRES_DB}'
      - 'AFN_POSTGRES_HOST=${_AFN_POSTGRES_HOST}'
      - 'AFN_POSTGRES_PORT=${_AFN_POSTGRES_PORT}'
      - 'AFN_APP_USER=${_AFN_APP_USER}'
      - 'AFN_APP_PASSWORD=${_AFN_APP_PASSWORD}'
      - 'AFN_ENV=${_AFN_ENV}'