version: "3.3"
services:
  ########## WEB APP ##########
  africannameswebapp:
    build: .
    restart: always
    container_name: africannames-webapp
    depends_on:
      - africannames-postgres-db
    ports:
    - "8080:8080"
    networks:
      - african-names-network
    environment:
      SPRING_PROFILES_ACTIVE: ${AFN_ENV}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${AFN_POSTGRES_HOST}:${AFN_POSTGRES_PORT}/${AFN_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${AFN_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${AFN_POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SECURITY_USER_NAME: ${AFN_APP_USER}
      SPRING_SECURITY_USER_PASSWORD: ${AFN_APP_PASSWORD}
      PROD_URL_HOST: ${AFN_POSTGRES_HOST}
      PROD_DB: ${AFN_POSTGRES_DB}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
      FIREBASE_DYNAMIC_LINKS_API_KEY: ${FIREBASE_DYNAMIC_LINKS_API_KEY}
      FIREBASE_DYNAMIC_LINKS_DOMAIN_URI_PREFIX: ${FIREBASE_DYNAMIC_LINKS_DOMAIN_URI_PREFIX}
      FIREBASE_DYNAMIC_LINKS_ANDROID_FALLBACK_LINK: ${FIREBASE_DYNAMIC_LINKS_ANDROID_FALLBACK_LINK}
      FIREBASE_DYNAMIC_LINKS_IOS_FALLBACK_LINK: ${FIREBASE_DYNAMIC_LINKS_IOS_FALLBACK_LINK}

  ########## WEB APP DATABASE ##########
  africannames-postgres-db:
    image: postgres:13.2-alpine
    container_name: africannames-postgres-db
    restart: always
    ports:
    - "5432:5432"
    networks:
      - african-names-network
    environment:
      POSTGRES_USER: ${AFN_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AFN_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AFN_POSTGRES_DB}
      volumes:
        ./postgres-data:/var/lib/postgresql/data
    profiles:
      - dev

  ########## FRONTEND ##########
  africannamesfront:
    build: ./src/main/frontend
    container_name: africannames-front
    depends_on:
      - africannameswebapp
    ports:
      - "80:80"
    networks:
      - african-names-network

networks:
  african-names-network:
    driver: bridge