version: "3.3"
services:
  ########## WEB APP ##########
  africannameswebapp:
    build: .
    restart: always
    container_name: africannames-webapp
    depends_on:
      - africannames-postgres-db
    ports:
    - "8080:8080"
    networks:
      - african-names-network
    environment:
      SPRING_PROFILES_ACTIVE: ${AFN_ENV}

  ########## WEB APP DATABASE ##########
  africannames-postgres-db:
    image: postgres:13.2-alpine
    container_name: africannames-postgres-db
    restart: always
    ports:
    - "5432:5432"
    networks:
      - african-names-network
    environment:
      POSTGRES_USER: ${AFN_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AFN_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AFN_POSTGRES_DB}
      volumes:
        ./postgres-data:/var/lib/postgresql/data
    profiles:
      - dev

  ########## FRONTEND ##########
  africannamesfront:
    build: ./src/main/frontend
    container_name: africannames-front
    depends_on:
      - africannameswebapp
    ports:
      - "80:80"
    networks:
      - african-names-network

networks:
  african-names-network:
    driver: bridge