/*
 * Copyright (c) 2022.
 * @Author Otourou Da Costa
 */

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS language;
DROP TABLE IF EXISTS firstname;
DROP TABLE IF EXISTS firstname_translation;
DROP TABLE IF EXISTS user_roles;

CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE country
(
    id    BIGINT NOT NULL,
    title VARCHAR(255),
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE language
(
    language_code           VARCHAR(255) NOT NULL,
    name                    VARCHAR(255),
    name_in_native_language VARCHAR(255),
    CONSTRAINT pk_language PRIMARY KEY (language_code)
);

CREATE TABLE firstname
(
    id               BIGINT NOT NULL,
    firstname        VARCHAR(255),
    gender           VARCHAR(255),
    meaning          VARCHAR(1024),
    meaning_more     VARCHAR(2048),
    origins          VARCHAR(255),
    regions          VARCHAR(255),
    countries        VARCHAR(255),
    nearing_names    VARCHAR(255),
    celebration_date VARCHAR(255),
    celebrities      VARCHAR(255),
    soundurl         VARCHAR(255),
    size             VARCHAR(255),
    create_date_time TIMESTAMP WITHOUT TIME ZONE,
    update_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_firstname PRIMARY KEY (id)
);

CREATE TABLE firstname_translation
(
    id                     BIGINT NOT NULL,
    meaning_translation    VARCHAR(255),
    origins_translation    VARCHAR(255),
    language_language_code VARCHAR(255),
    firstname_id           BIGINT,
    CONSTRAINT pk_firstname_translation PRIMARY KEY (id)
);

ALTER TABLE firstname_translation
    ADD CONSTRAINT FK_FIRSTNAME_TRANSLATION_ON_FIRSTNAME FOREIGN KEY (firstname_id) REFERENCES firstname (id);

ALTER TABLE firstname_translation
    ADD CONSTRAINT FK_FIRSTNAME_TRANSLATION_ON_LANGUAGE_LANGUAGECODE FOREIGN KEY (language_language_code) REFERENCES language (language_code);

CREATE TABLE user_roles
(
    user_id    BIGINT NOT NULL,
    role_id    INTEGER NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
    );

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
