apiVersion: v1
kind: Service
metadata:
  name: africannames-postgres-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: africannames-postgres-db
status:
  loadBalancer: {}