apiVersion: apps/v1
kind: Deployment
metadata:
  name: africannamesfront
  labels:
    app: africannamesfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: africannamesfront
  template:
    metadata:
      labels:
        app: africannamesfront
    spec:
      containers:
        - image: ghcr.io/tooflex/african-names-server/frontend:master
          name: africannames-front
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
