apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: africannameswebapp
  name: africannameswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: africannameswebapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/african-names-network: "true"
        io.kompose.service: africannameswebapp
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: afnsecrets
                  key: AFN_POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: afnsecrets
                  key: AFN_POSTGRES_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: afnsecrets
                  key: AFN_APP_USER
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: none
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: afnsecrets
                  key: AFN_APP_USER
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: afnsecrets
                  key: AFN_APP_PASSWORD
          image: registry.gitlab.com/african-names/back/african-names/africannames-webapp
          name: africannames-webapp
          ports:
            - containerPort: 8080
          resources: {}
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
status: {}
