openapi: 3.0.1
info:
  title: African Names App API
  description: African Names Discovering App
  version: "0.1"
servers:
  - url: http://localhost:8080
    description: Development environment URL
paths:
  /api/v1/firstnames/{id}:
    put:
      tags:
        - firstname-resource
      summary: Update a firstname
      operationId: updateFirstname
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Firstname'
        required: true
      responses:
        "200":
          description: Firstnames updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Firstname'
        "400":
          description: Bad request
        "404":
          description: No firstname found
    delete:
      tags:
        - firstname-resource
      summary: Delete a firstname
      operationId: deleteFirstname
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "400":
          description: Bad request
        "404":
          description: No firstname found
        "200":
          description: Firstnames updated
  /api/v1/translations/import:
    post:
      tags:
        - firstname-translation-resource
      summary: Import firstnames via .csv file
      operationId: uploadCsvFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Firstname'
        "400":
          description: Bad request
        "404":
          description: No firstname found
  /api/v1/newsletter/subscribe:
    post:
      tags:
        - mail-chimp-resource
      summary: Subscribe to African Name App newsletter
      operationId: subscribeToNewsletter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscribeNewsletterRequest'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/v1/firstnames/import:
    post:
      tags:
        - firstname-resource
      summary: Import firstnames via .csv file
      operationId: uploadCsvFile_1
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "400":
          description: Bad request
        "404":
          description: No firstname found
        "200":
          description: Firstnames retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Firstname'
  /api/v1/firstnames/:
    post:
      tags:
        - firstname-resource
      summary: Create a firstname
      operationId: createFirstname
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Firstname'
        required: true
      responses:
        "400":
          description: Bad request
        "403":
          description: Forbidden
        "201":
          description: Firstnames created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Firstname'
  /api/v1/auth/signup:
    post:
      tags:
        - auth-resource
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/v1/auth/login:
    post:
      tags:
        - auth-resource
      summary: Authenticate user
      operationId: authenticateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "400":
          description: Bad request
        "404":
          description: User not found
        "401":
          description: Unauthorized
        "200":
          description: User authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
  /api/v1/translations:
    get:
      tags:
        - firstname-translation-resource
      summary: Get firstname translations
      operationId: findFirstnameTranslations
      parameters:
        - name: lang
          in: query
          required: false
          schema:
            type: string
            default: en
        - name: pageable
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        "400":
          description: Bad request
        "404":
          description: No firstname found
        "200":
          description: Firstname Translations retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirstnameTranslationResponse'
  /api/v1/translations/firstnames/{id}:
    get:
      tags:
        - firstname-translation-resource
      summary: Get firstname translations
      operationId: findFirstnameTranslationsByFirstname
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Get firstname by Id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FirstnameTranslation'
        "400":
          description: Bad request
        "404":
          description: No firstname found
  /api/v1/translations/firstnames/{firstnameId}/lang/{langId}:
    get:
      tags:
        - firstname-translation-resource
      summary: Get firstname translations
      operationId: findFirstnameTranslationByFirstnameAndLang
      parameters:
        - name: firstnameId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: langId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Get firstname by Id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FirstnameTranslation'
        "400":
          description: Bad request
        "404":
          description: No firstname found
  /api/v1/newsletter/ping:
    get:
      tags:
        - mail-chimp-resource
      summary: Ping MailChimp API
      operationId: ping
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/v1/newsletter/members:
    get:
      tags:
        - mail-chimp-resource
      summary: Get all members of the newsletter list
      operationId: getSubscribers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/v1/firstnames:
    get:
      tags:
        - firstname-resource
      summary: Get firstnames list
      operationId: findFirstnames
      parameters:
        - name: lang
          in: query
          required: false
          schema:
            type: string
            default: en
        - name: pageable
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: Firstnames retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirstnameResponse'
        "400":
          description: Bad request
        "404":
          description: No firstname found
  /api/v1/firstnames/search:
    get:
      tags:
        - firstname-resource
      summary: Search firstnames
      operationId: searchFirstnames
      parameters:
        - name: specs
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/SpecificationFirstname'
      responses:
        "400":
          description: Bad request
        "404":
          description: No firstname found
        "200":
          description: Firstnames retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Firstname'
  /api/v1/firstnames/random:
    get:
      tags:
        - firstname-resource
      summary: Get random list of firstnames
      operationId: findPrenomsAlea
      parameters:
        - name: lang
          in: query
          required: false
          schema:
            type: string
            default: en
        - name: pageable
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        "400":
          description: Bad request
        "404":
          description: No firstname found
        "200":
          description: Firstnames retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Firstname'
  /api/v1/firstnames/paged:
    get:
      tags:
        - firstname-resource
      summary: Get firstnames list (paginated)
      operationId: findPagedFirstnames
      parameters:
        - name: lang
          in: query
          required: false
          schema:
            type: string
            default: en
        - name: pageable
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        "400":
          description: Bad request
        "404":
          description: No firstname found
        "200":
          description: Firstnames retrieved page by page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirstnameResponse'
components:
  schemas:
    Firstname:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
            - MIXED
            - UNDEFINED
        meaning:
          type: string
        meaningMore:
          type: string
        origins:
          type: string
        regions:
          type: string
        countries:
          type: string
        nearingNames:
          type: string
        celebrationDate:
          type: string
        celebrities:
          type: string
        soundURL:
          type: string
        size:
          type: string
          enum:
            - SHORT
            - MEDIUM
            - LONG
        createDateTime:
          type: string
          format: date-time
        updateDateTime:
          type: string
          format: date-time
    SubscribeNewsletterRequest:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    SignupRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        roles:
          uniqueItems: true
          type: array
          items:
            type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    JwtResponse:
      type: object
      properties:
        jwt:
          type: string
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string
    Pageable:
      type: object
      properties:
        sort:
          $ref: '#/components/schemas/Sort'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
    FirstnameTranslation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        meaningTranslation:
          type: string
        originsTranslation:
          type: string
        language:
          $ref: '#/components/schemas/Language'
        firstname:
          $ref: '#/components/schemas/Firstname'
    FirstnameTranslationResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/FirstnameTranslation'
        pageable:
          $ref: '#/components/schemas/Pageable'
        totalElements:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
        empty:
          type: boolean
    Language:
      type: object
      properties:
        languageCode:
          type: string
        name:
          type: string
        nameInNativeLanguage:
          type: string
    Sort:
      type: object
      properties:
        unsorted:
          type: boolean
        sorted:
          type: boolean
        empty:
          type: boolean
    FirstnameResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Firstname'
        pageable:
          $ref: '#/components/schemas/Pageable'
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int32
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        size:
          type: integer
          format: int32
        first:
          type: boolean
        number:
          type: integer
          format: int32
        empty:
          type: boolean
    SpecificationFirstname:
      type: object
